### ISSUE TITLE
Change section home page

### ISSUE THREAD

**Issue by xFerchoVJ** [xFerchoVJ/site-femme#1]
Se necesita definir que imagen y que textos irán en el banner dentro del home
- Imagen
- Textos

**Comment by xFerchoVJ** [comment]
![Image](https://github.com/xFerchoVJ/site-femme/assets/76576025/e84f44c3-d438-467c-b321-75a145aec7a1)

**Comment by mivcm** [comment]
La imagen ya está en la carpeta del drive

**Comment by mivcm** [comment]
- Editar tipografía: (Script título, todo lo demás Montserrat)
- Cambiar texto
- Cambiar imagen del banner
