### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by mivcm** [xFerchoVJ/site-femme#10]
Edita la información del footer:

- Dejar las secciones (enlaces) del nav
- Enlazar las redes sociales (Facebook e instagram)
- Editar tipografía y frase
- Eliminar "our services"
- En contacto sólo dejar el celular y el mail
- Checar colorimetría según la marca

**Comment by xFerchoVJ** [comment]
Falta solo la info de los enlaces a FB e Ig, celular y email
