### ISSUE TITLE
Alliances / Viva Market

### ISSUE THREAD

**Issue by mivcm** [xFerchoVJ/site-femme#28]
En la parte de Alianzas de la sección Viva Market, los títulos tienen enlaces (?), al darle clic te manda al inicio de la página, yo creo que es mejor quitarlos, que se vea el cambio de color al pasar el mouse o así, pero que no te redirija a nada, qué opinas?

![Image](https://github.com/xFerchoVJ/site-femme/assets/57143879/2b995334-3ea1-4faf-8ed8-df06bbc306b7)

**Comment by xFerchoVJ** [comment]
Yes
